### ISSUE TITLE
Image shows in incorrect orientation

### ISSUE THREAD

**Issue by KHellkvist** [Flipboard/FLAnimatedImage#100]
Having the FLAnimatedImageView showing a FLAnimatedImage in a UITableViewCell I sometimes get the animated GIF showing in the wrong orientation.
Scrolling sometimes makes the image show correct at another time.
Anyone having the same problem or had it before?
```c
imageLazilyCachedAtIndex: 
```
in
```c
displayDidRefresh:
```
row 248
seems to return the image in correct orientation when debugging, but still result in the wrong orientation when drawn.

**Comment by samnoble** [comment]
One way this can happen:

Use a contentMode like UIViewContentModeScaleAspectFit, and set a (static) image that requires rotation and scaling. I.e. [UIImage imageWithCGImage:something scale:2 orientation:<not Up>].

Now replace the static image with an animated image that requires different scale / orientation in order to appropriately fit in the view using the specified contentMode.

This happens "because" the FLAnimatedImageView directly manipulates its layer (by setting the contents to a CGImageRef), even though the UIImageView (the superclass) owns it. The UIImageView appears to configure it in a way that the FLAnimatedImageView doesn't expect.

**Comment by timonus** [comment]
Can you provide a sample GIF or project?

**Comment by samnoble** [comment]
Are you unable to replicate this behavior using the instructions I've provided?

**Comment by timonus** [comment]
@samnoble ah yes, I can reproduce it. Sample branch that repros available [here](https://github.com/Flipboard/FLAnimatedImage/tree/orientation-issue).

**Comment by greedyrouter** [comment]
@samnoble Thanks for your hints here. So I treat the static image as an animated image with 1 frame and infinite recurrence interval and fixed my issue.

**Comment by liuyihan** [comment]
@greedyrouter I also meet this problem, can tell me more detail?

**Comment by yuchensc** [comment]
@liuyihan In my case, I have two different types of cells, one is a static image cell, the other is an animated image cell. So I just created different cell reuse identifiers for both of them, to make the cells not interfere with each other.

**Comment by matrush** [comment]
This issue still exists, any clue why it's closed?
