### ISSUE TITLE
Make loopCount writable so one can set the animation loop count

### ISSUE THREAD

**Issue by codepushr** [Flipboard/FLAnimatedImage#83]
Hey guys,

first of all great library! I have the scenario where I want to be able to animate a GIF only once but I don't want to modify the GIF because on other places I do want the infinitive loop.

I found the `loopCount` property on `FLAnimatedImage` which when I modify the `readonly` flag and set it to 1 gives me exactly the outcome I want.

Is it possible to make it writable without me having to fork it?

**Comment by raphaelschaad** [comment]
Hi – thanks for opening this issue.

I'm not convinced yet that making the immutable properties of a GIF writable is the best way to go. Consequently, the same would have to happen e.g. with delay times.

Here is an approach with a loop completion block: https://github.com/Flipboard/FLAnimatedImage/pull/60/files

I'll think more about it. Any input is welcome!

**Comment by cemo** [comment]
#60 seems like a natural fit. Any chance to merge it?

**Comment by x1024** [comment]
I would second making the loop count and delay times writable. I tried several different methods to make a gif not loop. It works in a browser, but not in FLAnimatedImage.  
I'm not placing any blame in FLAnimatedImage, because GIF is perhaps a more complex standard than is reasonable.

But it would save a great deal of hair-pulling if I could just set an integer property, instead of wrestling with command-line tools that cater to an arcane spec.

**Comment by dalu93** [comment]
+1

**Comment by dharmendrajadav** [comment]
@dalu93  How to use **loopCompletionBlock** in swift 3?

**Comment by DuongQuangLoc** [comment]
@dalu93  
In swift 3
self.imageView.loopCompletionBlock = { (uint: UInt) -> Void in
// unit is the loop time of image.
            self.imageView.stopAnimating()
        }
