### ISSUE TITLE
Set `Require Only App-Extension-Safe API` to `Yes` under build settings

### ISSUE THREAD

**Issue by aventurella** [Flipboard/FLAnimatedImage#84]
Enables the framework to be included in App Extensions. Everything still builds just fine.

**Comment by raphaelschaad** [comment]
Thanks for opening the issue and the detailed description.

This issue has been fixed in a recently merged PR. The commit is this: https://github.com/cybertk/FLAnimatedImage/commit/3dfeba5cd295086608171613c6ecd7fc226d3e59

It's already on master and will be included in the shortly upcoming version 1.0.9.
