### ISSUE TITLE
GIF not animating at the original speed

### ISSUE THREAD

**Issue by hipwelljo** [Flipboard/FLAnimatedImage#98]
I'm exporting a GIF from Photoshop, and placing it into a view controller which is part of a page view controller. I'm noticing the frame rate does not match the original GIF frame rate - it's played back much slower than the original GIF, but only when run on a physical device - I tested the iPhone 6 and iPad 2. When run on the Simulator it animates at the correct speed. Has anyone else seen this, what do you think the problem is? Could our settings be incorrect when exporting the GIF to cause it to give iOS troubles playing it? Any tips and suggestions are appreciated.

**Comment by geelenstef** [comment]
Hi there,

You've found a solution yet? Because i'm facing the same problem atm !

Thanks

**Comment by arriaowlia** [comment]
If your GIF was exported with below-than-minimum frame delays, those frames will be processed and played back with a relaxed frame delay.

Look for the the definition of "kDelayTimeIntervalMinimum" in "initWithAnimatedGIFData:scale:" of FLAnimatedImage.m. It is set at 0.02s in my local copy. If your frame delay is lower than this value, it will be processed and played at 0.1s (five times the minimum time interval), i.e. "kDelayTimeIntervalDefault". Glancing at the code around this area will give you a good idea of what may change regarding frame delays.

**Comment by mserougi** [comment]
I'm facing the same problem. The exported gif has a frame delay of 0.03.

**Comment by timonus** [comment]
`FLAnimatedImage` does not guarantee absolutely perfect playback rates, it's designed to match as closely as it can but on slower devices or under memory pressure it may lag. You can see this in the sample project by looking at the red frame delay graphs when pressing the "Simulate Memory Warning" button.

Can you provide a sample GIF that exhibits this behavior for us to investigate?

**Comment by hipwelljo** [comment]
Sorry, I no longer have the gifs we saw the issue with. Our team was able to alleviate the problem quite a bit by reducing the resolution of the gif, but it still didn't meet expectations for smooth animation. We ended up trashing those gifs and using video files. Perhaps someone else who's encountering the same thing can provide a gif.

**Comment by mserougi** [comment]
I can provide a gif with the issue: https://dl.dropboxusercontent.com/u/522237/onboarding-main.gif

I should note that I've found a different library that plays the gif perfectly, but the library has its own share of other problems: https://github.com/mayoff/uiimage-from-animated-gif

The device I'm using to play the gif is an iPhone 6 Plus, so hardly a slow one.

**Comment by timonus** [comment]
Yeah, generating animated `UIImages` can be expensive and you don't get per-frame timing.

**Comment by mserougi** [comment]
@timonus So you're saying there's no way for this library to play the sample gif at its original speed? Is there anything that I can do with the gif itself?

**Comment by timonus** [comment]
@mserougi I am not saying that this library won't play the sample GIF at it's original speed. `FLAnimatedImage` will play GIFs as closely as it can to their accurate timings given sufficient device resources, it depends on the environment you're playing in.

Per https://github.com/Flipboard/FLAnimatedImage/issues/98#issuecomment-157483260, you may have frame delays under the minimum permitted delay, or there might be something else going on. I'll investigate with the GIF you provided at some point.

**Comment by mserougi** [comment]
@timonus Thank you, appreciate any insight you're able to provide.

**Comment by timonus** [comment]
Alright, I investigated a bit. Your GIF was very helpful!

Turns out, the dimensions and number of frames in this GIF put it into our "low memory" performance category, seen [here](https://github.com/Flipboard/FLAnimatedImage/blob/master/FLAnimatedImage/FLAnimatedImage.m#L322). This means frames are loaded on demand with minimal prefetching of additional frames, which causes inaccuracies in the frame delays. You can see this buy running the sample GIF in our demo app.

![screen shot 2015-12-08 at 9 20 19 am](https://cloud.githubusercontent.com/assets/522951/11662701/edaf6e92-9d8c-11e5-90d8-2e76e498d837.png)

I wrote an experimental change a while back that would resolve this at https://github.com/timonus/FLAnimatedImage/commit/75cf9a0f2e9af3faa7d7a1099177d788fbf0dba6. It dynamically chooses an appropriate cache size rather than fitting GIFs into certain boxes. There may be performance drawbacks in doing that, namely that every GIF tries to fill 10MB (`kFLAnimatedImageIdealMemoryFootprint `) which might not be ideal if you're loading multiple GIFs. Prior to that, large GIFs would only fill a few frames. That could be solved with something like having all `FLAnimatedImage`s have a memory quota to not be exceeded, which is something else I prototyped a while back.

In any case, I've cleaned up that change as https://github.com/Flipboard/FLAnimatedImage/tree/dynamic-memory-category on the main fork of this project. You can see the performance improved in [this video](https://www.dropbox.com/s/6l6hm7nx03g8zqx/sample%20copy-12-8-2015-34810.mov?dl=0). If you'd still like to use FLAnimatedImage for your project I'd recommend using that branch. Might consider merging that to master at some point!

**Comment by mserougi** [comment]
@timonus Glad I could help! This looks very promising indeed and the gifs in my project are playing much more smoothly now. Thank you!

**Comment by Imperiopolis** [comment]
Is this project still being maintained? 

I'd love to see this fix get merged into a release as I'm encountering similar issues with a larger gif and the changes on the `dynamic-memory-category` branch pulled onto master fix it right up.

**Comment by picturehit** [comment]
awesome !
